timerring/bilitool

.gitignore
biliupload/upload/bili_upload.py
pyproject.toml
requirements.txt

1. Replace the customized library `requests_html` with the general library `Requests`.
@timerring

build: change package dependencies

---

README-en.md
README.md
biliupload/cli.py
biliupload/config.json
biliupload/ioer.py
biliupload/upload/bili_upload.py
biliupload/utils/parse_yaml.py
template/example-config.yaml

Restore the upload parameters and write the logic for updating multiple parameters.
- fix a parameter issue in upload requests
- write the updating multiple parameters function
@timerring

feat: restore upload parameters

---

README-en.md
README.md
biliupload/cli.py
pyproject.toml

New build version 0.0.2
@timerring

build: build version 0.0.2

---

biliupload/cli.py
biliupload/login/check_login.py

Add the check login function.
- Add check login module.
@timerring

feat: add check login module

---

biliupload/cli.py
biliupload/config.json
biliupload/ioer.py
biliupload/login/login_bili.py
biliupload/login/logout_bili.py

Add the logout module, due to the bilibli official risk control the requests lib when sending the logout request, thereby I use the original http.client to implement it.
@timerring

feat: add logout module

---

biliupload/cli.py
biliupload/config.json
biliupload/controller/download_controller.py
biliupload/controller/upload_controller.py
biliupload/download/bili_download.py
biliupload/ioer.py

Add download module.
@timerring

feat: add download module

---

README-en.md
README.md
pyproject.toml

Build new version 0.0.3
@timerring

build: build version 0.0.3

---

biliupload/download/bili_download.py
biliupload/ioer.py

Refactor headers decorator to make the request more concise.
@timerring

refactor: add headers decorator

---

biliupload/authenticate/wbi_sign.py

Due to the official risk control, some requests need to be signed by the WBI algorithm to pass the restriction.
For more detail, refer to https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/sign/wbi.md
@timerring

feat: add wbi sign module

---

biliupload/cli.py
biliupload/feed/__init__.py
biliupload/feed/bili_video_list.py
tests/test_feed.py

Add list the uploaded video status module, which can query the video progresses, and get the reject reason if there needs some adjustment.Add a module for listing the uploaded video status. This module enables users to query the progress of videos and obtain the rejection reason in case any adjustments are required. 
- add a new cli subcommand
- add list module
- add test case
@timerring

feat: list uploaded videos module

---

LICENSE
README-en.md
README.md
bilitool/authenticate/config.json
bilitool/authenticate/ioer.py
bilitool/authenticate/wbi_sign.py
bilitool/cli.py
bilitool/controller/download_controller.py
bilitool/controller/upload_controller.py
bilitool/download/bili_download.py
bilitool/feed/__init__.py
bilitool/feed/bili_video_list.py
bilitool/login/check_login.py
bilitool/login/login_bili.py
bilitool/login/logout_bili.py
bilitool/upload/bili_upload.py
bilitool/utils/get_ip_info.py
bilitool/utils/parse_cookies.py
bilitool/utils/parse_yaml.py
pyproject.toml
tests/test_feed.py
tests/test_get_ip_info.py

Due to the expansion of functions, the project needs to be renamed and some structures adjusted to accommodate a broader spectrum of application scenarios. 
Therefore, the `biliupload` will be renamed as the `bilitool`.
- rename the package
- adjust the license
- adjust the cookie and ioer into `authenticate` module.
@timerring

refactor: adjust structure and rename project

---

README-en.md
README.md
bilitool/cli.py

Build the production verison.
@timerring

build: production version v0.1.0

---

bilitool/utils/get_ip_info.py
tests/test_utils.py

Write a decorator to avoid print useless info when calling the unittest module.
- add a decorator in `get_ip_info`
@timerring

refactor: optimize the unittest preformance

---

bilitool/cli.py
bilitool/utils/check_format.py
tests/test_utils.py

Add the convert module to get the both bvid and avid of the video.
- add bvid and avid convert module
- add some test cases
@timerring

feat: add vid convert module

---

bilitool/cli.py
bilitool/utils/check_format.py

Can support both the bvid and avid download.
@timerring

feat: support both vid download

---

README-en.md
README.md
bilitool/cli.py
pyproject.toml
requirements.txt

Build new version v0.1.1
@timerring

build: build version v0.1.1

---

.github/workflows/main.yml

Integrate the [Nuitka build Action](https://github.com/Nuitka/Nuitka-action) to facilitate usage across different platforms.
@timerring

ci: add nuitka build ci

---

sha256sum.sh

Include the shasum script to make it easier to verify the integrity of each release file.
@timerring

chore: add shasum script

---

bilitool/cli.py
bilitool/controller/download_controller.py
bilitool/download/bili_download.py

Add detailed logs in `download` module.
@timerring

perf: add detailed logs

---

bilitool/cli.py
pyproject.toml

build: build version v0.1.2

---

bilitool/login/login_bili.py
bilitool/model/config.json
bilitool/model/model.py

add client access key
@timerring

feat: add access key

---

README-en.md
README.md
bilitool/cli.py
bilitool/controller/upload_controller.py
bilitool/login/login_bili.py
bilitool/model/config.json
bilitool/model/model.py
bilitool/upload/bili_upload.py
tests/test_upload.py

- Add append function.
- Adjust the api from web api to the client api.
- Add the `sid` parameter to the login file.
fix #40 
@timerring

feat: append function

---

bilitool/feed/bili_live_list.py
tests/test_feed.py

Add live info function and corresponding test.
@timerring

feat: add live info

---

README-en.md
README.md
bilitool/controller/upload_controller.py
bilitool/upload/bili_upload.py

Auto speed test before the upload process, and select the best line.
fix #39 
@timerring

feat: auto select best line

---

bilitool/cli.py
bilitool/controller/upload_controller.py
bilitool/upload/bili_upload.py

chore: adjust the log

---

README.md
bilitool/cli.py
bilitool/controller/upload_controller.py
bilitool/model/config.json
bilitool/model/model.py
bilitool/utils/parse_yaml.py
docs/upload.md
template/example-config.yaml

Romve line parameter due to #44 
@timerring

fix: remove lines

---

bilitool/cli.py
bilitool/controller/login_controller.py
bilitool/login/login_bili.py

Add new function: login via cookie file.
@timerring

feat: login via cookie

---

bilitool/controller/feed_controller.py
bilitool/controller/upload_controller.py
bilitool/feed/bili_video_list.py
bilitool/upload/bili_upload.py

Add new function return uploaded video dictionary.
@timerring

feat: add video dict

---

README-en.md
README.md
bilitool/__init__.py
bilitool/authenticate/wbi_sign.py
bilitool/cli.py
bilitool/controller/download_controller.py
bilitool/controller/feed_controller.py
bilitool/controller/login_controller.py
bilitool/controller/upload_controller.py
bilitool/download/bili_download.py
bilitool/feed/bili_video_list.py
bilitool/login/check_bili_login.py
bilitool/login/login_bili.py
bilitool/login/logout_bili.py
bilitool/upload/bili_upload.py

Change from absolute import to relative import, to facilitate the bilitool used as a package.
@timerring

refactor: change relative import

---

bilitool/controller/upload_controller.py

Adjust the return format for the status of append result.
@timerring

fix: return format
